@startuml 演習2-4
left to right direction
package 社員{
actor 出荷担当者
actor 人事担当
}


rectangle 販売管理システム{
usecase 注文した商品の確認
usecase 商品の出荷業況の登録
}
rectangle 従業員登録システム{
usecase 社員情報の変更
usecase 社員情報の登録
usecase 社員情報の参照
}
出荷担当者 -->注文した商品の確認
出荷担当者 -->商品の出荷業況の登録
人事担当 -->社員情報の登録
人事担当 -->社員情報の変更
社員 -->社員情報の参照
社員 -->人事担当 :<<変更届の提出>>

@enduml