@startuml 演習2-4
left to right direction
actor 出荷担当者
actor 人事担当
actor 社員


rectangle 販売管理システム{
usecase 注文商品を確認する
usecase 商品の出荷状況の登録をする
}
rectangle 従業員登録システム{
usecase 社員情報の変更をする
usecase 社員情報の登録をする
usecase 社員情報の参照をする
}
出荷担当者 -->注文商品を確認する
出荷担当者 -->商品の出荷状況の登録をする
人事担当 -->社員情報の登録をする
人事担当 -->社員情報の変更をする
社員 -->社員情報の参照をする
社員 -->人事担当 :<<変更届の提出をする>>

@enduml