@startuml カレー
start
:米を洗う;
:米と水を炊飯器に入れる;
:炊飯器のスイッチを押す;
fork
:米が炊き上がるのを待つ;
fork again
:野菜を切る(玉ねぎはなるべく小さく、ジャガイモは一口サイズに切る);
:肉を大きめに切る;
:肉と野菜を炒める;
:水と炒めた肉と野菜を入れて中火で煮込む;
:具材に火が通ったら火を止めてルーを入れる;
:ルーが溶けたら弱火でとろみが付くまで煮込む;
end fork
:炊き上がった米とルーを混ぜて完成;
stop
@enduml