@startuml 演習3-1
class 従業員{
    ---
+ {abstract}出勤する:void
+ {abstract}給料をもらう:void
}
class 派遣{
    ---
+ 出勤する:void
+ 給料をもらう:void
}
class 契約社員{
    ---
+ 出勤する:void
+ 給料をもらう:void
}
class 正社員{
    ---
+ 出勤する:void
+ 給料をもらう:void
}
従業員 <|--派遣
従業員 <|--契約社員
従業員 <|--正社員
@enduml