@startuml 演習6-3 ステートマシン
left to right direction
[*]-->メニュー :システム接続
メニュー-->予約と確認 :予約か確認をする場合
予約と確認-->あなたの順番 :名前と電話番号を入力し登録ボタンを押した場合
予約と確認-->あなたの順番 :名前か電話番号を入力し確認ボタンを押した場合
予約と確認-->メニュー :名前か電話番号を入力し取消ボタンを押した場合
あなたの順番-->メニュー :メニューへボタンを押した場合
メニュー-->今の順番 :今の順番ボタンを押した場合
今の順番-->今の順番 :現在の患者番号を一つ増やす
メニュー-->[*] :おわりボタンを押した場合
@enduml