@startuml 3-5
object "<u>利用者情報1:利用者</u>" as u1{
名前=Aさん
}
object "<u>利用者情報2:利用者</u>" as u2{
名前=Bさん
}
object "<u>部屋情報1:部屋</u>" as r1{
    部屋名=301号室
    タイプ=シンプル
    価格=1100円
    キャンペーン価格=9000円
}
object "<u>部屋情報2:部屋</u>" as r2{
    部屋名=302号室
    タイプ=シンプル
    価格=1100円
    キャンペーン価格=9000円
}
object "<u>部屋情報3:部屋</u>" as r3{
    部屋名=303号室
    タイプ=シンプル
    価格=1100円
    キャンペーン価格=9000円
}
object "<u>ホテル情報:ホテル</u>" as h1{
    ホテル名=ホテルUML
}
h1 *-- r1
h1 *-- r2
h1 *-- r3
u1 -- r1
u2 -- r3
@enduml