@startuml 演習2-8
left to right direction
actor 利用者
actor ホテル従業員
actor ホテル管理者
rectangle ホテル予約システム{
usecase (<u>予約</u>\n拡張点\nキャンペーン期間) as 部屋の予約をする
usecase キャンペーン
usecase ログイン
usecase 空室状況の入力をする
usecase 空室状況の閲覧をする
usecase 予約の集計をする
usecase 会員登録
}
 空室状況の入力をする<--ホテル従業員
 部屋の予約をする<--利用者
空室状況の閲覧をする<--利用者 
 予約の集計をする<--ホテル管理者
キャンペーン ..>部屋の予約をする:<<extend>>
ログイン <.. 部屋の予約をする:<<include>>
ログイン <.. 空室状況の入力をする:<<include>>
ログイン <.. 空室状況の閲覧をする:<<include>>
ログイン <.. 予約の集計をする:<<include>>
会員登録 <. ログイン:<<include>>
@enduml