@startuml 3-7
object "<u>顧客情報1:顧客</u>" as c1{
    氏名=大坪直之さん
    住所
    来店日=12月30日
}
object "<u>顧客情報2:顧客</u>" as c2{
    氏名=高田利恵さん
    住所
    来店日=12月23日
}
object "<u>重要顧客情報:重要顧客</u>" as i1{
    氏名=高橋洋平さん
    住所
    来店日=11月21日
}
object "<u>注文情報1:注文</u>" as a1{
    数量=2台
    注文日=11月21日
}
object "<u>注文情報2:注文</u>" as a2{
    数量=1台
    注文日=11月21日
}
object "<u>注文情報3:注文</u>" as a3{
    数量=1台
    注文日=12月23日
}
object "<u>商品情報1:商品</u>" as b1{
    商品名=テレビ
    型式=V12345
}
object "<u>商品情報2:商品</u>" as b2{
    商品名=冷蔵庫
    型式=R8765
}
object "<u>商品情報3:商品</u>" as b3{
    商品名=プロジェクター
    型式=P1122
}
i1 -- a1
a1 -- b1
a3 -- b2
a2 -- b2
i1 -- a2
c2 -- a3
c1 -- b3 :熱心に見ていた
@enduml