@startuml 演習4-6
hide footbox
actor ":ユーザ" as actor
participant ":ブラウザ" as boundary
participant ":WEBサーバ" as control
participant ":画像サーバ" as entity
activate actor
actor -> boundary :リンクをクリックする
activate boundary
boundary -> control :画像ファイル名を渡す
activate control
control -> entity :画像ファイルを探す命令をする
activate entity
entity -> entity :画像ファイルを探す
control <<-- entity :画像ファイル
boundary <<-- control :画像ファイルとHTML
actor <<-- boundary :画像の閲覧

@enduml