@startuml 演習6-3 ステートマシン
left to right direction
[*]-->メニュー :システム接続
メニュー-->予約と確認 :予約と確認ボタンを押す
予約と確認-->あなたの順番 :名前と電話番号を入力し登録ボタンを押す
予約と確認-->あなたの順番 :名前か電話番号を入力し確認ボタンを押す
予約と確認-->メニュー :名前か電話番号を入力し取消ボタンを押す
あなたの順番-->メニュー :メニューへボタンを押す
メニュー-->今の順番 :今の順番ボタンを押す
メニュー<--今の順番 :メニューへボタンを押す
メニュー-->[*] :おわりボタンを押す
@enduml