@startuml 演習4-5
hide footbox
actor ":会員" as actor
participant ":商品検索画面" as boundary <<boundary>>
participant ":商品検コントローラ" as control <<control>>
participant ":商品" as entity <<entity>>
participant ":商品カテゴリ" as entity2 <<entity>>
activate actor
actor -> boundary :商品検索(商品番号)
activate boundary
boundary -> control :商品検索(商品番号)
activate control
create entity
control -->> entity :<<create>> (生成)
loop 商品カテゴリの数
create entity2
control -->> entity2:<<create>> 生成()
control -> entity :商品カテゴリ設定()
activate entity
deactivate entity
end loop
boundary <<-- control :商品情報()
boundary -> boundary :商品情報表示(商品情報)
activate boundary

@enduml